### ISSUE TITLE
Fix problems with Color template

### ISSUE THREAD

**Issue by rec** [rec/timedata#59]
I saw this and put it in the code!

https://github.com/rec/tada/blob/master/src/tada/color/color.template.pyx#L139-L140

Might eliminate it as part of the larger "generic type" explosion.

**Comment by bentoncbainbridge** [comment]
Tom, let's have a webchat about typical color schemes in video, like YUV

Benton C Bainbridge | +1.646.338.9172 | bentoncbainbridge.com
<bentoncbainbridge@bentoncbainbridge.com>
Creators Project on Moving Pictures Gallery
http://thecreatorsproject.vice.com/blog/a-new-model-for-selling

**Comment by rec** [comment]
I am *very* interested, but right now, I really need to know ZERO about how
the actual mathematics work - that's a detail sketched in at the very end.

Basically, RGB -> YUV to me is "some function taking three numbers to three
numbers" :-D and my plan is to be able to organize all sort of these
functions coherently.

I'm free today though I'm probably back on hashing things mostly...

On Fri, Jun 3, 2016 at 10:23 AM, Benton C Bainbridge <
notifications@github.com> wrote:

> Tom, let's have a webchat about typical color schemes in video, like YUV
>
> Benton C Bainbridge | +1.646.338.9172 | bentoncbainbridge.com
> <bentoncbainbridge@bentoncbainbridge.com>
> Creators Project on Moving Pictures Gallery
> http://thecreatorsproject.vice.com/blog/a-new-model-for-selling
>
> On Thu, Jun 2, 2016 at 4:56 PM, Tom Swirly <notifications@github.com>
> wrote:
>
> > I saw this and put it in the code!
> >
> >
> >
> https://github.com/rec/tada/blob/master/src/tada/color/color.template.pyx#L139-L140
> >
> > Might eliminate it as part of the larger "generic type" explosion.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/rec/tada/issues/59>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ALQTyeF0BAiA5pK6jCLSG078Hkjz5XfPks5qH0OPgaJpZM4Is-T7
> >
> > .
> >
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rec/tada/issues/59#issuecomment-223592566>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAPdsidpb0IPBV8Dy5vuYVbWWV3AwVG2ks5qIDjagaJpZM4Is-T7>
> .
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by rec** [comment]
This is all fixed in the new code!

https://github.com/rec/tada/blob/x-master/src/tada/template/one/magic_arithmetic.pyx
